version: '3.4'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
        environment:
          - discovery.type=single-node
          - http.host=0.0.0.0
          - transport.host=127.0.0.1
          - xpack.security.enabled=false
          - ES_JAVA_OPTS=-Xms750m -Xmx750m
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - esnetwork
    kibana:
        image: docker.elastic.co/kibana/kibana:6.7.0
        ports:
            - "5601:5601"
        networks:
            - esnetwork
        depends_on:
            - elasticsearch

volumes:
    esdata:
        driver: local
networks:
    esnetwork:
        driver: bridge